# Generated by Django 4.1.6 on 2023-02-11 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='name')),
                ('name_latin', models.CharField(max_length=64, unique=True, verbose_name='name_latin')),
                ('description', models.TextField(max_length=500, null=True, verbose_name='description')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 2, 11, 19, 23, 31, 320659), verbose_name='created_at')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='updated_at')),
            ],
        ),
    ]
