# Generated by Django 4.1.6 on 2023-02-11 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 11, 19, 27, 3, 520388), verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='name_latin',
            field=models.CharField(max_length=64, unique=True, verbose_name='name latin'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='updated_at',
            field=models.DateTimeField(null=True, verbose_name='updated at'),
        ),
    ]
