# Generated by Django 4.1.6 on 2023-02-11 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0002_alter_bird_created_at_alter_bird_name_latin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 11, 19, 29, 0, 730546), verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='updated at'),
        ),
    ]
