# Generated by Django 4.1.6 on 2023-02-11 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0003_alter_bird_created_at_alter_bird_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 11, 19, 30, 31, 216452), verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='description'),
        ),
    ]
