# Generated by Django 4.1.6 on 2023-02-11 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0004_alter_bird_created_at_alter_bird_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infraclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='description')),
            ],
        ),
        migrations.AlterField(
            model_name='bird',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 11, 20, 13, 16, 820935), verbose_name='created at'),
        ),
    ]
