# Generated by Django 4.1.6 on 2023-02-12 06:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0015_country_watch_watched_at_alter_bird_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='birds.country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bird',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 12, 6, 44, 39, 78199), verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 12, 6, 44, 39, 78757), verbose_name='created at'),
        ),
    ]
