# Generated by Django 4.1.6 on 2023-02-12 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0016_watch_country_alter_bird_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 12, 6, 46, 29, 972695), verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 12, 6, 46, 29, 973257), verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='watched_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='watched at'),
        ),
    ]
