# Generated by Django 4.1.6 on 2023-02-18 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0019_alter_bird_created_at_alter_watch_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 18, 13, 52, 28, 467968), verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 18, 13, 52, 28, 468526), verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='watched_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 18, 13, 52, 28, 468517), verbose_name='watched at'),
        ),
    ]
