# Generated by Django 4.1.6 on 2023-02-18 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0020_alter_bird_created_at_alter_watch_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 18, 15, 36, 16, 177607, tzinfo=datetime.timezone.utc), verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 18, 15, 36, 16, 178172), verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='watched_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 18, 15, 36, 16, 178162), verbose_name='watched at'),
        ),
    ]
