# Generated by Django 4.1.6 on 2023-02-18 15:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0024_alter_bird_created_at_alter_watch_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='watched_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='watched at'),
        ),
    ]
