# Generated by Django 4.1.6 on 2023-02-18 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0027_alter_watch_watched_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='watched_at',
            field=models.DateField(default=datetime.date(2023, 2, 18), verbose_name='watched at'),
        ),
    ]
