# Generated by Django 4.1.6 on 2023-02-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0029_alter_watch_watched_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='watch',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
    ]
