# Generated by Django 4.1.6 on 2023-02-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0033_country_created_at_country_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='updated at'),
        ),
    ]
