# Generated by Django 4.1.6 on 2023-02-19 09:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0034_alter_watch_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='country',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='infraclass',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at'),
        ),
    ]
